### ISSUE TITLE
Error in run

### ISSUE THREAD

**Issue by tanyagupta** [gwg-women/gwg-women-techmakers#11]
@khusbuchandra getting an error in final stages of running the app. When you get the chance could you look at it please ? 

![image](https://user-images.githubusercontent.com/8497274/36062439-d18d3ab6-0e3a-11e8-88d2-f15808cc2b80.png)

**Comment by tanyagupta** [comment]
This may just be an issue from my side, in which case, we can close it out and I can investigate further

**Comment by digilou** [comment]
@tanyagupta My build went well. I just pulled in the updates, add my Google key, and ran it. However, I have another issue I have to solve on my end, probably concerning my key because my map didn't load correctly.

**Comment by sgluzins** [comment]
@digilou did you resolve your API key issue? I tried getting everything set up yesterday and I can't get past a google maps API error in the console "error: ApiNotActivatedMapError" I tried creating a new key also but no luck.

**Comment by digilou** [comment]
Oh yes! @sgluzins I had the same issue. I had to enable the Google Maps JavaScript API. It took me way to long to figure it out!
https://console.developers.google.com/apis/library/maps-backend.googleapis.com/?filter=category:maps&id=fd73ab50-9916-4cde-a0f6-dc8be0a0d425&project=pro-platform-194817

**Comment by sgluzins** [comment]
@digilou WOO! Thank you so much. That solved it for me :) I'll add that in the wiki for the set up instructions

**Comment by digilou** [comment]
That's a GREAT idea @sgluzins! Thanks for doing that.

**Comment by tanyagupta** [comment]
Thanks from me too!

**Comment by tanyagupta** [comment]
So you guys have it working  @digilou and @sgluzins ? Probably something from my side then. I'll try again

**Comment by khusbuchandra** [comment]
Sorry, I missed the mails. Are we good now? or any issues with the setup? . @tanyagupta  this is what I did for installing jQuery `npm install --save jQuery` Its added as part of dependency and should get installed.

**Comment by sgluzins** [comment]
@tanyagupta @khusbuchandra - I am good on my end. My issue was with the key and it is all resolved now!

**Comment by khusbuchandra** [comment]
I am closing this issue as its working with key.
