### ISSUE TITLE
Update instructions for new location of key

### ISSUE THREAD

**Issue by tanyagupta** [gwg-women/gwg-women-techmakers#13]
Currently the guide refers to "master". This needs to be removed

**Comment by digilou** [comment]
I've updated the wiki to include the .env Google API key updates made in #12 and #14. Maybe we should update the README with a link: [Setup Instructions](https://github.com/gwg-women/gwg-women-techmakers/wiki/Set-Up-Instructions)?

**Comment by khusbuchandra** [comment]
Yes, we should definetly update the README with recent changes related to API key.
