### ISSUE TITLE
Service worker not working?

### ISSUE THREAD

**Issue by amr08** [gwg-women/gwg-women-techmakers#130]
Items store as cached when online, but when testing offline I am not getting the cached content.  

Checking here to see if someone has tested out the SW offline or if this is just something on my end? If not, the service worker is not fully functional.   If it is working for others, I apologize for the noise!

![screen shot 2018-03-29 at 7 56 48 pm](https://user-images.githubusercontent.com/17239196/38118865-a56f3396-338b-11e8-8589-9bbf3792d372.png)

**Comment by amr08** [comment]
Showing my online view for comparison: 
![screen shot 2018-03-29 at 8 03 04 pm](https://user-images.githubusercontent.com/17239196/38118925-3b63b1a6-338c-11e8-91f6-17b48364db24.png)

**Comment by agonzalez0515** [comment]
Thanks for checking! I asked Sonali and Khusbu to check on their machines before merging and it worked for them, but I did feel things were a little fragile. We did find that "offline" mode on the browser was not working, so we all tested with wifi off instead.

This is what I see with wifi off. The styles and the static map should be cache.

![screen shot 2018-03-29 at 7 59 31 pm](https://user-images.githubusercontent.com/21042658/38122779-11b84a6a-338c-11e8-8e19-89dd16605d37.png)

**Comment by amr08** [comment]
@agonzalez0515 Thanks for the response - relieved to hear/see this! 🙂   That _is_ really strange that it doesn't like offline mode... Although I'll leave this untouched as you are right, it seems like a pretty delicate situation with a lot of moving pieces.
