### ISSUE TITLE
Enhancement: Create style that highlight a place item box when user hover over it. Related to issue #133

### ISSUE THREAD

**Issue by resant18** [gwg-women/gwg-women-techmakers#134]

**Comment by khusbuchandra** [comment]
@resant18 , shall i assign this issue to you?

**Comment by resant18** [comment]
Yes, I'll work on it.

**Comment by resant18** [comment]
@digilou, Could we reopen the issue? The styling doesn't apply yet since I haven't generate the mini css. Could anyone lead me a way on how to generate the file?

**Comment by digilou** [comment]
Oh, yes! Sorry @resant18!  What editor do you use? I use a plugin for VS code that minifies my CSS files: CSS Minify.

**Comment by resant18** [comment]
No problem! I didn't realize there is mini css now. I use WebStorm. I will try to find if it has similar plugin.

**Comment by digilou** [comment]
If you need any more help @resant18, I'll do what I can.
