### ISSUE TITLE
Footer: convert div into ul

### ISSUE THREAD

**Issue by digilou** [gwg-women/gwg-women-techmakers#148]
Related to #81 

Like how JSON was used, but semantically the list of contributors in the footer should leverage the `ul` element rather than just a `div`.

JavaScript will need to be revised to iterate list items. Update CSS, as needed.

**Comment by PepperAddict** [comment]
I'll take this one on. I needed to update the names in it anyway and this will be a quick javascript/html fix. 
This will change app.js 's JSX, description.js's javascript/JSON and the CSS to adjust list styles accordingly.
