### ISSUE TITLE
Finalize wireframe

### ISSUE THREAD

**Issue by tanyagupta** [gwg-women/gwg-women-techmakers#15]
Wireframe available here. Need someone to take over edit rights, accept any suggestions and finalize it

https://wireframepro.mockflow.com/view/gwgwomen#/page/8171874e854b45e18321556694c276ed

**Comment by tanyagupta** [comment]
Hi guys, please comment here on any changes you would like. For major changes, please send me your email address so I can provide access for editing

**Comment by digilou** [comment]
@gwg-women/all-gwg-women I think it looks like a good start. It shows our feature intentions, and there's always room for design tweaks as we go.

**Comment by tanyagupta** [comment]
Closed still but opening a new issue to refine this further
