### ISSUE TITLE
Edit current or set up new skeleton page and complete component 1 through 8

### ISSUE THREAD

**Issue by tanyagupta** [gwg-women/gwg-women-techmakers#16]
The components are as follows. If you only want to do some of them, split it up and open a new issue for the elements you are not working on
- [x] 1 = header and favicon
- [x] 2 = search box
- [x] 3 = assuming a JSON object of name, rating image and text, design a sidebar
- [x] 4 = map - image file for now
- [x] 5 = Wiki information assuming basic information (JSON) of a place
- [x] 6 = sticky footer
- [x] 7 = map - image file for now
- [x] 8 = assuming an object similar to 3, display sidebar
Use Google material design if it makes sense

Modify current google maps to display in a smaller area, given lat/long based on geolocation

**Comment by digilou** [comment]
This is another issue I definitely don't mind sharing. I love front-end challenges, but want to give others a chance to work on the fun stuff, too.

**Comment by digilou** [comment]
Related to #1 and #8.

**Comment by digilou** [comment]
Wonderful @rixamix! I haven't started yet, so feel free to choose whichever part you'd like to start. Probably the best way is to create a new issue specific to the thing(s) you want to tackle, and go for it! That way we can tackle each thing at a time and my branch won't mess with your branch. Plus, if others join in, they can tackle individual pieces, as well, building off of what you've built and submitted.

**Comment by agonzalez0515** [comment]
I can help with one or two of these components. Who's working on which? Are we all using Material Design? A framework?

**Comment by digilou** [comment]
@agonzalez0515 You can definitely help with this! I haven't picked anything yet, as I was juggling another issue. @rixamix have you started anything? Handlebars was installed for templating, but not other frameworks that I see.

**Comment by agonzalez0515** [comment]
Cool! I'll work on the sidebar component for 3 and 8. I opened a new issue for it.

**Comment by replimes** [comment]
I’ll work on 6 - sticky footer.  I picked the color as #D8E83D.

**Comment by digilou** [comment]
@replimes @agonzalez0515 @rixamix I'll take 1: header and favicon, to start.

**Comment by rixamix** [comment]
I'm working on 2  the search box right now

**Comment by rixamix** [comment]
well... i got a searchbox put together but looking at the code for the skeleton it looks like it's already in there.

**Comment by khusbuchandra** [comment]
@gwg-women/all-gwg-women , we have the inital react setup in done by  @agonzalez0515.  Now we can start on the other components and have the skeleton take shape.

**Comment by sonalikatara** [comment]
The current dev branch gave me a compilation error on npm start
`
Failed to compile.

	./src/index.js
	Module not found: /Users/sonali/webProjects/gwd-women/gwd-women-techmakers/gwg-women-techmakers/src/App.js does not match the corresponding path on disk app.js.
`

It's a minor change that needs to be done and everything works smoothly.

**Comment by sonalikatara** [comment]
@agonzalez0515 I saw you mentioned the service workers need to be put back in, I can take care of it.

**Comment by khusbuchandra** [comment]
@rixamix , Issue #47 is for implementing the search box. We need to add autocomplete feature to it. If you are still interested in search box, I will assign it to you.

**Comment by agonzalez0515** [comment]
@khusbuchandra I think the map search box component already comes with autocomplete. Or is this not what y'all mean by autocomplete?

![screen shot 2018-03-03 at 10 47 02 am](https://user-images.githubusercontent.com/21042658/36937992-3ba03930-1ed0-11e8-8e0b-3068f697ac79.png)

**Comment by khusbuchandra** [comment]
@agonzalez0515 , Ahh.. somehow two days back I didn't see the autocomplete coming up, although I checked again now and it seems to work perfectly. My bad, I assumed autocomplete service needs to be added. I will close the issue now.
We can refactor intialMap, with search style in a separate file though. Should we also be displaying some more detail on click of marker?

**Comment by khusbuchandra** [comment]
With all component done. Closing this issue.
