### ISSUE TITLE
Recenter button on map to get the map center to user location 

### ISSUE THREAD

**Issue by khusbuchandra** [gwg-women/gwg-women-techmakers#162]
At present we don't have any interface for user to recenter the map based on its location. If user searches for some location or place of interest, the position value changes and there is no way to set the user location back again. Shall we add a button like google map to recenter to user's location?

**Comment by sonalikatara** [comment]
Yes @khusbuchandra We can add a button that says 'where am I' or recenter . We will need to create a new state for it in App. I can make a pr and everyone can take a look at it and decide.

**Comment by khusbuchandra** [comment]
That would be great @sonalikatara . Can't wait to see it in action. All pieces are coming together.
