### ISSUE TITLE
Add loading spinner/splash screen while map is loading users geolocation

### ISSUE THREAD

**Issue by sgluzins** [gwg-women/gwg-women-techmakers#163]
It is recommended to not load the users geolocation on initial load of the webpage. As a result, we have decided to add user-friendly behavior so it is known that something is being processed.

A loading spinner/splash screen will be added while the current geolocation is being set in the background.

**Comment by khusbuchandra** [comment]
@sgluzins , how is it coming up? Let us know if you need any help with anything.

**Comment by sgluzins** [comment]
hi @khusbuchandra! unfortunately I got pretty sick the other day so I paused my work on this :( I am feeling 100x better now though so I am planning to get it implemented tonight. I will reach out if I have any troubles, thank you!
