### ISSUE TITLE
Improve styling for wiki component

### ISSUE THREAD

**Issue by sonalikatara** [gwg-women/gwg-women-techmakers#164]
I also feel there is extra padding above and below the wiki information. There is lot of space between the co-ordinates and the description/info if the results from wiki are just a few lines. it works well when the info is 7-8 lines but again if it is a more then that it doesn't look nice

**Comment by sonalikatara** [comment]
@PepperAddict wrote this on a PR and I am pasting it here so that we can continue the conversation here
@sonalikatara what's funny is that that was the exact subject I wanted to bring up. The places sidebar has a set height to avoid it from stretching everything else.
I don't know how to have it an auto height but contained inside the container(if that makes any sense)
I put my location as new york with its long description and noticed it doesn't look very nice with a long description. I was thinking of having places the same height as the map and then give description the whole column. Let's talk about more style suggestions in an issue I'm going to create.

**Comment by PepperAddict** [comment]
![description](https://user-images.githubusercontent.com/4171505/38264812-27bf7568-3742-11e8-9adf-265d929be586.png)

i wrote note on the picture. Are we on the same page on the edit promised? (I added my suggestion too)

**Comment by sonalikatara** [comment]
@PepperAddict 
Like your suggestion of aligning to top and removing the space, maybe we can make the color of the coordinates info different to pop it out.

Making description go the whole width , doesn't  look good to me.

Your screen shot looks good to me, maybe we can just increase the places component's size  a little bit more.

**Comment by PepperAddict** [comment]
I have an idea about about the coordinates and the description. What if coordinates has a different background to separate it from description rather than space?  I'll have to take screenshots to show what looks nice. let me do that real quick.

**Comment by sonalikatara** [comment]
ha ha we are reading each other's mind. Please make the changes when you have time and send a pr
Sorry didn't see that this issue is not assigned yet, Do you want to take care of this ?

**Comment by PepperAddict** [comment]
LOL I think we kind of had the same idea for coordinates and submitted it at the same time. Let me try different things and see what looks good.  I'll post it here and maybe we can do a vote.

**Comment by PepperAddict** [comment]
![des3](https://user-images.githubusercontent.com/4171505/38269825-9da0bd52-374f-11e8-87d9-c9653a71a59a.png)

hmm sorry it took me a while. I was trying to figure out where the mysterious gap under the map was coming from.  
Well I'm sure there's more ways to go about this but I personally like the border way. Let me know which you prefer or if you have more ideas.

**Comment by sonalikatara** [comment]
Thank you for giving us options pepper. My vote goes to bold

**Comment by khusbuchandra** [comment]
I love the bold too @PepperAddict . I really like all the ideas floating around here. I also have one suggestion not sure to take it up in this issue itself. It's about Wiki data, now i had mentioned earlier that i don't get any wiki data for my location at times I see 'Wiki Request Failed' in place of Wiki Component. If no wiki is available, I would rather have it blank than showing the user that wiki request failed. I would be interested to know what you all feel about it? Sorry for hijacking the post for it.

**Comment by PepperAddict** [comment]
@khusbuchandra That's a good point. If you feel that way then most likely others feel the same.  I'll make it blank instead of a tacky message.  Or... maybe... we can think of something else to replace that.. Like maybe a wiki summary of Earth? LOL 
I think bold is winning. I'll wait till tomorrow to finalize the style just in case there are more ideas to improve the description area.

**Comment by sonalikatara** [comment]
Yes we should catch the error and show anything. It’s part of the wiki so
wouldn’t call it hijacking 🤠

**Comment by PepperAddict** [comment]
![des4](https://user-images.githubusercontent.com/4171505/38283413-eaa60bc8-3783-11e8-98be-b32802059759.png)

Earth is now the default. I hope nobody has problems with that because I am loving it. lol

**Comment by sonalikatara** [comment]
@PepperAddict   are you using milligram ?

**Comment by PepperAddict** [comment]
Wait. I thought milligram was removed? Did it get put back in on accident somewhere?

**Comment by sonalikatara** [comment]
I remember you doing that in one of the pr’s but it’s back in , in the
current Dev branch. Look in app.js

**Comment by PepperAddict** [comment]
Yep, I see it in there. Strange. Would you like me to remove milligram in this PR for the wiki component or should I do separate PR for that. I had to modify app.js for the wiki. 

currently I'm trying to figure out a way to have wiki read the country only if it's outside of the usa , and if it still has issues, it'll go to earth as default.

**Comment by sonalikatara** [comment]
Going to earth was a smart solution, regarding milligram it's up to you, you can just add it to current pr if you want to since this pr is for style.

**Comment by PepperAddict** [comment]
okay the fallback to country is working great. I can't seem to test Earth since any obscure location throws an error with the geolocation.js file. 

![descri5](https://user-images.githubusercontent.com/4171505/38314666-c1e2f180-37f4-11e8-99dd-6546a84e903c.png)

**Comment by PepperAddict** [comment]
the milligram removal is going to be an easy fix. i'll fix that along with wiki.
edit>> well that explains the mysterious gap from the map

**Comment by sonalikatara** [comment]
Thank you Pepper, while testing can you run a build and test if your style
changes are reflected.

**Comment by PepperAddict** [comment]
![coords](https://user-images.githubusercontent.com/4171505/38321849-b963dcc4-3806-11e8-8caa-a09909dc8e0e.png)

ignoring the numbers in the city, i think the coords area should be improved too. Any ideas?  I think I should lowercase 'coordinates'.   right now it just looks like a run on sentence and it's bugging me. I need to separate city,state and its coordinates somehow.

**Comment by sonalikatara** [comment]
Add a line break before Coordinates. You can get the latitude and longitude
from the position returned by the api.
