### ISSUE TITLE
Remove Milligram from package.json dependencies

### ISSUE THREAD

**Issue by digilou** [gwg-women/gwg-women-techmakers#168]

**Comment by sonalikatara** [comment]
I can take care of this when I am working on my current issue. I thought we had gotten rid of it, but it is being imported in App.js too

**Comment by khusbuchandra** [comment]
@digilou , @sonalikatara  & @PepperAddict , I am getting this on Edge browser : 
![image](https://user-images.githubusercontent.com/35678241/38400507-ee821d04-396d-11e8-8b1e-c7518f4dc669.png)
 the gap between the  input and button seems to too much.  If its an easy fix, i would like to have it there.
Apart from that the Recenter map button overlaps like this in chrome and Edge both for me:
![image](https://user-images.githubusercontent.com/35678241/38400684-eed10b52-396e-11e8-95fc-e721bdca8b36.png)

Are any of you experiencing the same?

**Comment by digilou** [comment]
@khusbuchandra I haven't tested on Edge yet. WOW. Have you been testing with it earlier on? Is this the first time it's looked funky?

**Comment by khusbuchandra** [comment]
I have been testing on Edge for the map, but didn't notice that maybe , it slipped as i was focused on getting it at least open up on Edge. But while we are into styling right now , i got to see that.

**Comment by PepperAddict** [comment]
I think this can be closed now. 
I want to make a separate issue for all of the style fixes including post milligram removal.
