### ISSUE TITLE
Implement geolocation and weather API

### ISSUE THREAD

**Issue by tanyagupta** [gwg-women/gwg-women-techmakers#17]
Use a weather API and use geolocation to return the weather and location. This will be used in the frontend header
by 2/27

**Comment by ssspear** [comment]
I'd be interested in working with someone on this. Would anyone want to partner up and work with a beginner?

**Comment by khusbuchandra** [comment]
@ssspear  I can help out, you can DM me on slack.

**Comment by tanyagupta** [comment]
Hi guys, can  you tell me how you are returning the location ? Is it a lat/long combination ? I want to use a placeholder location for the Google Static Maps component. Thanks in advance!

**Comment by sgluzins** [comment]
@tanyagupta yup! Its with the lat/long combo. I'll send you a message with more info!

**Comment by khusbuchandra** [comment]
@sgluzins , Could you refactor the component as react components using geolocation and weather api? Let me know if you need any help.

**Comment by sgluzins** [comment]
@khusbuchandra yup, I'll work on it ASAP and get a PR out there. I had to fly to NC for work and I am flying back to the west coast tmrw night so I haven't had a chance to refactor it but I pulled down all the new changes.
