### ISSUE TITLE
Move styles from RecenterMapButton component to scss file

### ISSUE THREAD

**Issue by digilou** [gwg-women/gwg-women-techmakers#175]
Related to #172

**Comment by sonalikatara** [comment]
@digilou , I have the styles in css , please feel free to modify it
`.btnRecenter {
  backgroundColor:#fff;
  border: 2px solid #fff;
  borderRadius: 3px;
  cursor: pointer;
  boxShadow: 0 2px 6px rgba(0,0,0,.3);
  color: black;
  fontFamily: Roboto,Arial,sans-serif;
  padding: 6px 6px;
   margin: 7px;
  lineHeight: 24px;
  position: absolute;
  left: 110px;
  top: 3px;
}`

and then RecenterMapButton.js can reduce to

import React from 'react';

const Button = props => {

  const {recenterMyMap, mapCenter, ...other } = props;

  return <button className="btnRecenter"

          {...other}

      />

};
export default Button


Hope this helps

**Comment by digilou** [comment]
Yikes! I think I got ahead of you @sonalikatara. Please check my PR to make sure I did it right.
