### ISSUE TITLE
Warning from description.js wiki

### ISSUE THREAD

**Issue by sonalikatara** [gwg-women/gwg-women-techmakers#177]
`
./src/components/Description.js
  Line 21:  'counter' is assigned a value but never used  no-unused-vars
`

@PepperAddict can you take a look, i think this came from the last merged pr, sorry I missed it while reviewing

**Comment by PepperAddict** [comment]
whoops. I was trying all sorts of ways to give it a third fetch and missed this when clearing my trail. I'll fix this. Thanks you!
