### ISSUE TITLE
Google Places Component

### ISSUE THREAD

**Issue by tanyagupta** [gwg-women/gwg-women-techmakers#18]
Write a function that makes a call to Google places, given lat/long and returns a list of popular places
(dependency with issue #17 )
Display new map based on search term
Display pins based on search term

**Comment by sonalikatara** [comment]
Can this be assigned to me

**Comment by tanyagupta** [comment]
Sonali - you can go ahead and assign this to yourself (top right)

**Comment by tanyagupta** [comment]
Let me know if you have any trouble with that ?

**Comment by sonalikatara** [comment]
Tanya - I don't have the rights to assign. I think only people with owner and collaborator privileges can do that.

**Comment by tanyagupta** [comment]
Sorry about that, we should add you. I've assigned in the meanwhile

**Comment by sonalikatara** [comment]
Thank you Tanya. Right now I am setting up the project on my machine. Although I have worked with Github for a while this is my first time collaborating so just made my ssh key and forked the project.

**Comment by khusbuchandra** [comment]
@sonalikatara  I had assumed adding to team give the collaborator access as well, I have made the changes and you should have those privileges now.
