### ISSUE TITLE
Add ARIA to spinner

### ISSUE THREAD

**Issue by digilou** [gwg-women/gwg-women-techmakers#185]
I'm committing to research what the loader in #163 needs to be perceivable to non-sighted users. I know there's specific ARIA syntax that can be uses.

**Comment by sgluzins** [comment]
@digilou great idea! I didn't think of this when implementing so glad you are adding it in :)

**Comment by khusbuchandra** [comment]
Thanks @digilou , that's a great feature to have and would improve the accessibility.

**Comment by digilou** [comment]
Note to myself for when I get home to create a branch:
- `aria-live="polite"`
- `role="status"`
