### ISSUE TITLE
Install eslint-plugin-jsx-a11y

### ISSUE THREAD

**Issue by digilou** [gwg-women/gwg-women-techmakers#196]
Recommended by [Scott Vinkle](https://medium.com/@svinkle/creating-accessible-react-apps-38dc1c2775cf) to help identify accessibility problems in JSX:
https://github.com/evcohen/eslint-plugin-jsx-a11y

**Comment by agonzalez0515** [comment]
hey @digilou, I think create-react-app already uses `eslint-plugin-jsx-a11y` because i've definitely gotten a11y errors while compiling. 

https://github.com/facebook/create-react-app/blob/next/packages/eslint-config-react-app/package.json

**Comment by digilou** [comment]
Great! It looks like in Vinkle's article, he adds it to an .eslintrc file so it's spotted before it goes to DevTools.
