### ISSUE TITLE
Wikipedia component for Mappa (NOT for Mappa Wikipedia)

### ISSUE THREAD

**Issue by tanyagupta** [gwg-women/gwg-women-techmakers#2]
Modify wikipedia component

**Comment by replimes** [comment]
Newbie here - I’m having trouble with the setup of Cloud9 - Do you create an instance or connect over SSH, and if it’s SSH then what’s the host and user?
<img width="981" alt="screen shot 2018-02-21 at 5 15 56 pm" src="https://user-images.githubusercontent.com/36494738/36514876-bab147b6-172b-11e8-9e36-696745070dd0.png">

**Comment by PepperAddict** [comment]
Hey, I was thinking of putting images for the tutorial. Should I upload the images in git?

**Comment by tanyagupta** [comment]
@PepperAddict if you embed images in markdown when you are working on it locally that should work. You can save the image in an assets directory (do we have one?) or it can point to a url

**Comment by khusbuchandra** [comment]
@PepperAddict, Are you working on Wikipedia component ? how are progressing on this issue? Let me know if you need help with React.

**Comment by tanyagupta** [comment]
@PepperAddict I think the labelling for this issue was not precise enough. We have a project wikipedia where we share information about our project and we have a wikipedia component for our project. I think you were referring to the former. Can you confirm so I can open a new issue and make this one unassigned, and also add more details to this issue so it is clearer for others ?

**Comment by PepperAddict** [comment]
Hey Tanya! I was confused and thanks for catching that.

**Comment by tanyagupta** [comment]
Welcome! I just signed on for the wiki too, will add you, let's work
together on that

**Comment by PepperAddict** [comment]
I will try my best to finish this by tonight or tomorrow at the very latest. *crosses fingers* Did some research yesterday and it's beginning to make more sense to me.  I'll come forward if I have any questions, but for right now ... I'm pretty sure I can do it. Thank you @tanyagupta and @khusbuchandra for your supports. I won't let you gals down.

**Comment by tanyagupta** [comment]
Awesome!  Thanks Pepper
