### ISSUE TITLE
Develop new icons for the Mappa project (different from GWG Women's logo)

### ISSUE THREAD

**Issue by tanyagupta** [gwg-women/gwg-women-techmakers#20]
Icons(Finalize list) & Logo - 2/27/2018

**Comment by digilou** [comment]
Ooo, this would be so much fun! I'm assigning myself to play with ideas this week, but I have NO problem sharing it with other ideas. Please assign yourself if you want to present your own ideas so we can have different options to choose from.

**Comment by digilou** [comment]
@replimes Did you want to work on this, too?

**Comment by replimes** [comment]
@digilou Yeah, I can sketch out a few ideas for you.

**Comment by replimes** [comment]
A few ideas to consider @digilou 
![img_3321](https://user-images.githubusercontent.com/36494738/36514705-9e7d7ebc-172a-11e8-9038-b7e5d356cee4.jpg)

**Comment by digilou** [comment]
I love your cursive "Grow" @replimes! I was also thinking about a logo with the open/close tag theme. I'm also drawn to the ones with the woman's silhouette head and initials.

**Comment by digilou** [comment]
@replimes Do you need help making these digital?

**Comment by replimes** [comment]
@digilou Yes please!

**Comment by digilou** [comment]
@replimes Cool! I'll start working on it this weekend.

**Comment by digilou** [comment]
@PepperAddict I'm def open to your idea mentioned in Slack.

**Comment by PepperAddict** [comment]
![girlmap](https://user-images.githubusercontent.com/4171505/36986327-8d1b6468-2067-11e8-867a-58c97760f038.png)

Hey i put this one together.  If you want something changed let me know especially with the color. I don't know what our theme is going to be and I think it should really match it. If we decide something different later I can always change it then too. Let me know if you want the svg.

**Comment by PepperAddict** [comment]
![girlmap](https://user-images.githubusercontent.com/4171505/36986997-561cc7b6-2069-11e8-888d-72301a338c78.png)

oops. sorry i had to reupload. The marker was too bold and then it was too thin. I think one's just right. Let me know what to change with color to fit the theme of the project.

**Comment by tanyagupta** [comment]
Hi Pepper - can you also post the original b/w one here? We could use that as our logo on github

**Comment by PepperAddict** [comment]
![mapg1bw](https://user-images.githubusercontent.com/4171505/36996666-5e7b2e40-2085-11e8-96f7-369c7e9cbfa2.png)



Here you go. If you need an svg version that's scalable, let me know. It won't let me upload svg here.

**Comment by tanyagupta** [comment]
Posted as our new profile pic on Github. Thanks! that looks great

**Comment by tanyagupta** [comment]
@PepperAddict can I say it again? this is beautiful!
Will add a new task on project icons and will tag you, please feel free to untag if you wish

**Comment by tanyagupta** [comment]
Agreed @khusbuchandra 
@replimes @PepperAddict @digilou - are you guys still working on the icons ?

**Comment by PepperAddict** [comment]
Hey ladies!
Is there a design you wanted from @replimes ? Pick one and I can help digitize it. :)

**Comment by tanyagupta** [comment]
I like the  <imageofwoman/> but with a female sign instead


Also these are the sizes we would probably need:
"icons": [{
    "src": "images/touch/icon-128x128.png",
    "type": "image/png",
    "sizes": "128x128"
  }, {
    "src": "images/touch/apple-touch-icon.png",
    "type": "image/png",
    "sizes": "152x152"
  }, {
    "src": "images/touch/ms-touch-icon-144x144-precomposed.png",
    "type": "image/png",
    "sizes": "144x144"
  }, {
    "src": "images/touch/chrome-touch-icon-192x192.png",
    "type": "image/png",
    "sizes": "192x192"
  }],

**Comment by PepperAddict** [comment]
That's creative. I like it. It's very react-y.  haha.  sizes and types will be no problem with svg. Is this a final okay to get started or should we wait for everyone else's opinion? Either way I'm going to wait till tomorrow to get started on this.

**Comment by tanyagupta** [comment]
Nice!

**Comment by PepperAddict** [comment]
![idea](https://user-images.githubusercontent.com/4171505/38144280-0acd8ac2-3412-11e8-984b-07210258db2a.png)

Here's a rough sketch of the ideas before I digitize it. What do you ladies think? Any critique or ideas would be great. What would the colors be? I'd like the marker to be filled in. Actually, we don't even have to discuss the colors now since it'll be easily customizable. If the shape looks good to everybody I'll go ahead and finalize it.

**Comment by khusbuchandra** [comment]
I do like it. Would need the team @gwg-women/all-gwg-women  to check it out.

**Comment by resant18** [comment]
I like the tag idea! How bout add GWG in small size under the tag maybe?

**Comment by resant18** [comment]
Maybe not add the GWG. I picture the circle of female sign as circle in the marker now. 
![img_20180330_203511](https://user-images.githubusercontent.com/36322603/38159322-b9bb5ed6-345a-11e8-90f9-26e641e39a94.jpg)

**Comment by sonalikatara** [comment]
Wow! Looks great!

**Comment by PepperAddict** [comment]
![updated](https://user-images.githubusercontent.com/4171505/38169718-75df97c8-353f-11e8-8d71-d5a774f7b776.png)

Here's an updated combined idea. If that looks good just let me know what color and I'll finalize it with the many sizes.

**Comment by tanyagupta** [comment]
I really like it!

**Comment by khusbuchandra** [comment]
@PepperAddict , I like it too. Let's go with this one.

**Comment by digilou** [comment]
@PepperAddict I'm definitely liking it too.

**Comment by PepperAddict** [comment]
Whoops forgot about this. So I take it black is okay? 
I'll make it these sizes:
128x128
152x152
144x144
192x192

**Comment by PepperAddict** [comment]
[markerICON.zip](https://github.com/gwg-women/gwg-women-techmakers/files/1896870/markerICON.zip)

Here is the icon in the sizes listed above.

**Comment by khusbuchandra** [comment]
Thanks @PepperAddict

**Comment by sonalikatara** [comment]
Thank You @PepperAddict , Is it suppose to be our favicon  or should it be placed somewhere else too?
The format for the image for favicon must be 16x16 pixels or 32x32 pixels, using either 8-bit or 24-bit colors. The format of the image must be one of PNG (a W3C standard), GIF, or ICO. I can make those changes in the image but want to confirm if we need it anywhere else ?

**Comment by digilou** [comment]
@sonalikatara I think a favicon is good. I envisioned we could put this in the header, too. To the left of the Welcome. @tanyagupta @khusbuchandra @PepperAddict @replimes @resant18, what do you all think?

**Comment by sonalikatara** [comment]
Option 1
![mappa header option 1](https://user-images.githubusercontent.com/4163671/38598256-808e7a44-3d10-11e8-8a19-a1e1cc3aeeaa.png)

Option 2
![mappa header option 2](https://user-images.githubusercontent.com/4163671/38598310-b5bb0048-3d10-11e8-9fb9-0bcd31e50045.png)

Option3
![mappa header option 3](https://user-images.githubusercontent.com/4163671/38598398-042b7122-3d11-11e8-98c3-353b3923351f.png)

Do you want to add the logo to the header? Which option do you like ?

I like option 3.

**Comment by agonzalez0515** [comment]
I like 3 too!

**Comment by khusbuchandra** [comment]
3 looks good. We should go for it.

**Comment by digilou** [comment]
3 is what I envisioned.
