### ISSUE TITLE
Review current project map, wireframe and schedule and make updates as needed

### ISSUE THREAD

**Issue by tanyagupta** [gwg-women/gwg-women-techmakers#24]
Folks please review the timetable and deliverables and comment where needed.
Please also assign yourself open/help wanted tasks

**Comment by rixamix** [comment]
OK so after looking this over I'm just wondering is it that the site will initially load with the geolocation then you search for things nearby? or only get information after it's typed into the seach box?

**Comment by khusbuchandra** [comment]
Yes @rixamix , it would initially load user's location and nearby places in side bar and other details based on geolocation. These are also the details we intend to provide offline support for.

**Comment by tanyagupta** [comment]
Closing out this issue, no comments so hopefully the plan looks good to everyone.
