### ISSUE TITLE
clean up branches

### ISSUE THREAD

**Issue by tanyagupta** [gwg-women/gwg-women-techmakers#26]
Delete branches not being used. For instance we should probably delete development and stick  to dev. And also delete the branches associated with merged pull requests

**Comment by digilou** [comment]
Good question! I just deleted "update-readme" and "issue-1-service-worker" branches to keep it clean. Was wondering about the "development" branch.

**Comment by digilou** [comment]
I'm starting a Contribution Guidelines page in the wiki. Maybe that could be a step people take after their PR is merged?

**Comment by tanyagupta** [comment]
@digilou I think we can delete "development" @khusbuchandra can you verify ?
An update on contributions guidelines would be great

**Comment by khusbuchandra** [comment]
Yes, we should have only the dev and master branch, all the changes needs to be pushed to dev and periodically we would be merging all the stable changes to master branch.

**Comment by digilou** [comment]
"development" branch deleted.
