### ISSUE TITLE
Store a static map

### ISSUE THREAD

**Issue by tanyagupta** [gwg-women/gwg-women-techmakers#31]
This task is to store a default static map

**Comment by tanyagupta** [comment]
Sure
1) The purpose would be to have the static map cached and displayed even if
the app is offline (based on first geolocation)
2) The plan would be to store it in Cache using Cache API since this API
actually returns an image that can be stored

that is if it all works out...

**Comment by amr08** [comment]
@tanyagupta Thanks for the clarification - Sounds good I'll see what I can do! 🙂

**Comment by amr08** [comment]
@tanyagupta I got sidetracked by continuing to look into the service worker set up - I reopened issue #1   (but feel free to close again if registering was all that was needed).  My issue is that although cached, I am unable to fetch anything (getting undefined).  Not sure if something weird is going on in my end.  Just finished my own sw project so I'm trying to investigate this more.

**Comment by tanyagupta** [comment]
@khusbuchandra please advice if we are still doing this ? Too many changes to keep track lately but let's close if no longer needed

**Comment by khusbuchandra** [comment]
My only worry is about Google map not allowed to be cache. I am yet to do a full research on what's the right way to workaround it, and whether static map solves that issue. Mostly whatever i read leads to something like [this](https://stackoverflow.com/questions/3889142/is-it-allowed-to-cache-static-google-maps). If static map serves our purpose, then we are still going with it. 
Let me know if you find/know something interesting about it.

**Comment by tanyagupta** [comment]
Storing maps server-side is a no-no. But on the client side - it appears that is exactly what the API was built for. For our application we only aim to store the maps client side and with efficient caching only one map at a time. So I think it should be fine. However I was wondering with React, does it still make sense to use that ?
