### ISSUE TITLE
Sticky Footer

### ISSUE THREAD

**Issue by replimes** [gwg-women/gwg-women-techmakers#33]
I will do component number 6 from issue #16

**Comment by khusbuchandra** [comment]
@replimes , you can also checkout Google's Material UI for React . I even like there footer which just provides link to their GitHub's contributor list.

**Comment by replimes** [comment]
@khusbuchandra Thank you, I’ll be sure to research that a bit and try to implement it.

**Comment by PepperAddict** [comment]
HI, how is this one going? I'd like to be a part of this one.

**Comment by tanyagupta** [comment]
Thanks @PepperAddict. @replimes can @PepperAddict help out ?
@khusbuchandra

**Comment by replimes** [comment]
@PepperAddict Feel free to take over.  I haven’t worked with React before and haven’t gotten too far on this.  How does one go about importing a font?  @tanyagupta @khusbuchandra 

Here is all I have so far:
`
import React from 'react';
import ReactDOM from 'react-dom';
import {lime500, darkBlack} from 'material-ui/styles/colors';
import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';
import MyAwesomeReactComponent from './MyAwesomeReactComponent';

const App = () => (
  <MuiThemeProvider>
    <MyAwesomeReactComponent />
  </MuiThemeProvider>
);

const muiTheme = getMuiTheme({
  palette: {
    primary1Color: lime500,
    textColor: darkBlack,
  },
  appBar: {
    height: 50,
  },
});

ReactDOM.render(
  <App />,
  document.getElementById('app')
);

export default {
  fontFamily: 'Roboto, sans-serif',
  primary1Color: lime500,
  textColor: darkBlack,
}
`

**Comment by PepperAddict** [comment]
@replimes 
Do you want to upload what you put in just so you can get credit for your hard work?
If not, that's okay. I'm going to end up putting it into the css file instead though just to keep the styling organized into one place that way it'll be easier to debug a styling problem.

I will work on this this Saturday or Sunday. 
From my understanding from the conversation, we're going to be using the github's API to generate the info for us? Will fiddle around with this further when Saturday or Sunday rolls around.

**Comment by replimes** [comment]
@PepperAddict No thank you.  :-) Thanks for asking.  I don’t understand what you mean by using github’s API... I’m a complete newbie.

**Comment by PepperAddict** [comment]
I could not find a gathered info of all our members, but I did find contributors
https://api.github.com/repos/gwg-women/gwg-women-techmakers/contributors

Should I just use that or would you like all the members ? I do not mind adding them in manually. Just let me know what you all think.

**Comment by tanyagupta** [comment]
I think this should be fine, we can always add others in later @sonalikatara  @PepperAddict @khusbuchandra if you agree

**Comment by PepperAddict** [comment]
sounds good @tanyagupta . Less work for me right now, but if there's a name that should be added, let me know. I noticed that Renata isn't in there for some reason, so I'll put her in there.

**Comment by tanyagupta** [comment]
@PepperAddict are you using this ? https://blog.github.com/2013-05-16-personal-api-tokens/
