### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by tanyagupta** [gwg-women/gwg-women-techmakers#35]
1) Add install instructions
2) Take out Cloud9

**Comment by digilou** [comment]
@tanyagupta is it not working for Cloud9 users?

**Comment by tanyagupta** [comment]
It is working but it may be making it more complicated than it needs to be.
Either that or I need to improve the cloud9 instructions. One should not
have to go into the settings page that Kristine did. It should run right
off the bat

**Comment by agonzalez0515** [comment]
Just a quick awesome github fyi, we can use check boxes to show progress of things that need to be done and what's done.

- [ ] a task list item
- [ ] list syntax required
- [ ] normal **formatting**, @mentions, #1234 refs
- [ ] incomplete
- [x] completed

https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments

**Comment by tanyagupta** [comment]
Closing and moved to #62 with more details on waht will be done
