### ISSUE TITLE
Webpack for managing and bundling code

### ISSUE THREAD

**Issue by khusbuchandra** [gwg-women/gwg-women-techmakers#4]
Should we be using webpack for bundling the scripts? Or any other suggestions.

**Comment by tanyagupta** [comment]
Thanks @khusbuchandra - can you assign this to yourself if you agree ? (and close)

**Comment by khusbuchandra** [comment]
I have added Webpack and added jquery & babel as dependency to be installed from node. Still need to figure out about knockout. This would be an ongoing process of updating the config and package.json as we progress further.
