### ISSUE TITLE
Search component with autocomplete feature

### ISSUE THREAD

**Issue by khusbuchandra** [gwg-women/gwg-women-techmakers#47]
Make the Search Box as a separate React component

- [ ] Autocomplete feature - should return predictions for user input

- [ ] Input query on submit should result in search result

At present search part of InitialMap.js, refactor it to be a separate component.

**Comment by turisap** [comment]
Hi, @khusbuchandra, I'm currently looking for a first real contribution to an open-source project and would like to work on this issue. Can I do that?

**Comment by tanyagupta** [comment]
@turisap welcome and glad to hear you want to join an open source project. This is actually a class assignment for students - and I am not sure if you are with the GWG student team ? If so, please share your id on Slack. If not also let us know. We can make some suggestions about great open source project to join.

**Comment by turisap** [comment]
@tanyagupta,  unfortunately, I'm not a member of GWG student team, but would like to participate in a open-source project  and I will be happy to see your suggestions (it would be great if it will be something with React). Thanks)

**Comment by tanyagupta** [comment]
@turisap There are 3 react projects (here)[https://github.com/MunGell/awesome-for-beginners] under Javascript. However I am also asking my class colleagues to come up with suggestions and will come back with more.

**Comment by tanyagupta** [comment]
@turisap please contact Bryan on Slack  https://join.slack.com/t/devpath/shared_invite/enQtMzE2NDEzODI1Njg3LWZlOWY3ZTY3ZGFiYmQ0NTY2MDJmYjUwY2EzZDJjZGI4NmYwOGU2OTFjMDY2ZjA3YTc1YmE0ZDU0MDk3Y2ZjNWY

he can include you on a React/other open source project

**Comment by turisap** [comment]
@tanyagupta, thank you for your advice, I'll proceed with that)

**Comment by khusbuchandra** [comment]
Closing it as we are using Google searchbox feature.
