### ISSUE TITLE
Configure working code on static map generation and storage for React

### ISSUE THREAD

**Issue by tanyagupta** [gwg-women/gwg-women-techmakers#53]
See Issue 31 for details and PR 51

**Comment by khusbuchandra** [comment]
@tanyagupta , Would you like to work on it? I found a react component with static map [here](https://github.com/viatsko/react-google-static-map). You can try it, if that helps.

**Comment by tanyagupta** [comment]
@khusbuchandra not familiar with react. Perhaps @angelica since she is a react expert ?

**Comment by khusbuchandra** [comment]
@tanya, yesterday me, sonali & Angelica discussed about the components and sonali would like to take this one.

**Comment by khusbuchandra** [comment]
@agonzalez0515 , I am closing this issue wrt #113
