### ISSUE TITLE
create react app not registering env

### ISSUE THREAD

**Issue by PepperAddict** [gwg-women/gwg-women-techmakers#54]
For those that has this issue.
So I fixed it on my end, but boy did I do a ton of fiddling around and researching. 
Even when I had **REACT_APP_** in the beginning , my react app was still not reading that env file. I've tried all sorts of tricks while googling. But this worked... 

When googling, I came across this:

> The environment variables are embedded during the build time. Since Create React App produces a static HTML/CSS/JS bundle, it can’t possibly read them at runtime. To read them at runtime, you would need to load HTML into memory on the server and replace placeholders in runtime, just like described here. Alternatively you can rebuild the app on the server anytime you change them.
[link](https://github.com/facebook/create-react-app/tree/master/packages/react-scripts/template#adding-custom-environment-variables)

directed me to this: 

>If you’re hosting your build with a static hosting provider you can use react-snapshot or react-snap to generate HTML pages for each route, or relative link, in your application. These pages will then seamlessly become active, or “hydrated”, when the JavaScript bundle has loaded.

>There are also opportunities to use this outside of static hosting, to take the pressure off the server when generating and caching routes.

>The primary benefit of pre-rendering is that you get the core content of each page with the HTML payload—regardless of whether or not your JavaScript bundle successfully downloads. It also increases the likelihood that each route of your application will be picked up by search engines.

[link](https://github.com/facebook/create-react-app/tree/master/packages/react-scripts/template#pre-rendering-into-static-html-files)

Then finally followed this guy's steps and it works! *phew* 
[link to the steps to get snapshot guide](https://medium.com/superhighfives/an-almost-static-stack-6df0a2791319)

Though the only thing I really needed to do was 
  `yarn add react-router-dom react-helmet react-snapshot styled-components`

and 
`yarn build`

**Comment by tanyagupta** [comment]
Pepper thanks for the detailed explanation. It might be a good idea to post on #resources in Slack for anybody else working with React/Yarn

**Comment by khusbuchandra** [comment]
Thanks a lot Pepper for finding the solution. I was one of them facing this issue and it works now.
