### ISSUE TITLE
Header Component

### ISSUE THREAD

**Issue by sgluzins** [gwg-women/gwg-women-techmakers#55]
The header (component 1) from #16.

**Comment by khusbuchandra** [comment]
@sgluzins , there are new changes merged with google-maps-react package. Incorporate the new InitialMap component to set the map center based on geocode .

**Comment by sgluzins** [comment]
thanks @khusbuchandra. I will pull in those changes and make the modifications.

**Comment by khusbuchandra** [comment]
Add another issue for centering the map based on user's geocode details.
Closing this one.
