### ISSUE TITLE
GWG women's project wiki (about the project) including contributor info, set up

### ISSUE THREAD

**Issue by tanyagupta** [gwg-women/gwg-women-techmakers#62]
Add to the existing Mappa wiki and include contributor information, and clean up instructions

- [x] Design main wiki page 
- [x] Recommend package that provides a nicer look and feel 
- [x] Set up main wiki page
- [x]  Add Contributor section
- [x]  Remove working demo
- [x]  Clean up instructions
- [x]  Remove Cloud 9 instructions

**Comment by PepperAddict** [comment]
- [ ] Design main wiki page 
- [ ] Recommend package that provides a nicer look and feel 
- [ ] Set up main wiki page
- [ ]  Add Contributor section
- [x]  Clean up instructions
- [ ]  Add section on how to build up an open source project 
- [ ]  Remove working demo
- [x]  Remove Cloud 9 instructions

**Comment by tanyagupta** [comment]
@PepperAddict starting back on this issue. Just to confirm, the ones still open are the ones without the checkmark, right ?

**Comment by PepperAddict** [comment]
yeah it was. I downloaded it and put it in. Should I upload it that way we'll use our own?

**Comment by PepperAddict** [comment]
btw tanya if you figured out how to make it show,  could I see your code? :D

**Comment by tanyagupta** [comment]
@PepperAddict texted you on Slack about what you wanted to show? And yes, could you please upload it? I'll use it for the wiki

**Comment by tanyagupta** [comment]
@khusbuchandra @PepperAddict @agonzalez0515 @digilou @sonalikatara @desdemonhu @PepperAddict @sgluzins @amr08 @desdemonhu @M0nica
Requesting a review from you all on this page please:
https://gwg-women.github.io/gwg-women-techmakers/ before we close the issue

Contributors page has been added and Jekyll is being used
Also I see we are missing some contributors in the Github API call. So I suggest:
1) @PepperAddict could you run the API call to github again for an updated JSON (fyi for others the JSON from the API call result is being included manually on suggestions from team members)
2) For others I can create a template for folks to submit their information manually. 

Any feedback can be posted in this thread. Thanks in advance!

**Comment by PepperAddict** [comment]
Hey I just did one right now. Here's an updated:
https://api.github.com/repos/gwg-women/gwg-women-techmakers/contributors

the problem with this call though is that it doesn't show Renata and Monica which I know have been actively helping out. I created a new json file of my own to add the two here: ... okay they don't let me import json lol. i'll send it to you on slack.  
I put the update in the footer as well. I really wanted to be able to import a json file that way we can both work on that file together, but I never figured it out . Sorry about that.

**Comment by sonalikatara** [comment]
@tanyagupta it looks great. 
I digged a bit into why some of our contributors are not showing on the gitHub contributor's page or API results.

[https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/)

 @M0nica  @resant18

**Comment by sonalikatara** [comment]
@tanyagupta the part ' The repository uses the following files : ' was something I wrote to explain a bit about the files but can use some improvement  and more details. We can create a new issue for this.

Also,

```
* Description.js Contains the Wiki component that displays the Wikipedia information about the current city.

Header.js Get’s the current location and weather conditions and displays the information on the header.

InitialMap.js Get’s and displays the map with markers to the search results.

Places.js Displays the searchResults in the form of a list on the left side of the app.

PlacesListItem.js Contains the ListItems control that displays all the list items. It displays the name address and opening hours of a place.

Search.js Get’s the user Input for search query.

src/css/index.css Contains the styles of the App

src/services folder has the code that makes calls to the location, map and weather API’s and fetches their results.

geolocation.js

weather.js 
```

are all a subList under the heading 

`src/components: `

We need to add some details aboutr geolocation.js and weather.js and also add in staticmaps controller

**Comment by sgluzins** [comment]
hi @resant18! I actually had this issue where my email address was different so my commits weren't showing up initially :) 

In GitHub:
- go to settings
- emails (verify the email address listed here)

On your computer, open the terminal and run the following line:
git config --global user.email

Those should match up. If the email you have for git doesn't match the one in github then your contributions won't show up on your profile! There may be something else causing it but this solved it for me. Hopefully this helps.

**Comment by tanyagupta** [comment]
Thanks @sonalikatara and @sgluzins for the information
@resant18 were you able to fix this issue ?

**Comment by tanyagupta** [comment]
@sonalikatara I made the changes you requested. @PepperAddict thanks for the updated JSON - it worked perfectly. With this review I think we are in a good place so I am closing this issue. Thanks to everyone for their useful feedback and suggestions
@khusbuchandra @PepperAddict @agonzalez0515 @digilou @sonalikatara @desdemonhu @PepperAddict @sgluzins @amr08 @desdemonhu @M0nica

**Comment by resant18** [comment]
@tanyagupta, I will made PR tonight and will check it out. I'll update you after.
