### ISSUE TITLE
organizing the CSS

### ISSUE THREAD

**Issue by PepperAddict** [gwg-women/gwg-women-techmakers#65]
Going to put all of the CSS into one SASS/CSS file to organize it so we can easily modify it when we need to.

**Comment by digilou** [comment]
@PepperAddict @shaala I'll help pull out inline styles as I come across them while doing accessibility testing and combing code.

**Comment by PepperAddict** [comment]
I've searched far and wide. I think I've gathered them all. This can be closed now.
