### ISSUE TITLE
Clean up App.js and move viewmodel to separate files.

### ISSUE THREAD

**Issue by khusbuchandra** [gwg-women/gwg-women-techmakers#8]
Currently everything is in app.js . Ideally we should have separate functionality from app.js 
We can have a project structure defined and follow that set up. Feel free to assign yourself and suggest better ways to do it.

**Comment by agonzalez0515** [comment]
I noticed we're using Knockout. I've never worked with it before but doing a quick read it says it uses MVVM structure. Will we be refactoring the project to follow this structure?

**Comment by digilou** [comment]
@agonzalez0515 I have never used Knockout either, and have done even less research. @khusbuchandra installed that, I believe. And @desdemonhu installed Handlebars which is a templating framework. This issue is definitely related to what we're trying to tackle in #16.

**Comment by agonzalez0515** [comment]
I'm going to look into this so that we can refactor asap and avoid merge conflicts on app.js.

**Comment by khusbuchandra** [comment]
@digilou & @agonzalez0515 :  @Tanya had created the initial source code which was based out of one of the Udacity class assignment which required knockout. I think everyone would be fine with switching to another if all agree to do so, I myself is not familiar with Knockout, although I am still learning Angular 4 and React so don't know if can suggest anything :)
Whether we go with knockout or not, we need to definitely refactor the app.js

**Comment by agonzalez0515** [comment]
oh cool! i'm also currently learning react, so I would vote for that. Should we bring this up on Slack or on the team forum?

**Comment by khusbuchandra** [comment]
@agonzalez0515 , I think we can start the discussion on team forum, but would need to decide soon. As I see lot of work on various components have started.

**Comment by desdemonhu** [comment]
Also learning React!

**Comment by agonzalez0515** [comment]
Started discussion here https://github.com/orgs/gwg-women/teams/all-gwg-women/discussions/4. Will post on Slack as well.

**Comment by khusbuchandra** [comment]
As we have moved to React now, I am closing this issue.
