### ISSUE TITLE
Make app mobile responsive

### ISSUE THREAD

**Issue by digilou** [gwg-women/gwg-women-techmakers#92]
When working in DevTools I realized our components don't stack, shrink or adjust when accessed on mobile.
This is a great CSS challenge for someone looking to dig more into styling and media queries.

<img width="280" alt="screen shot 2018-03-24 at 10 14 26 am" src="https://user-images.githubusercontent.com/8865558/37867376-47e711aa-2f4c-11e8-8722-943dd165d2e9.png">

**Comment by digilou** [comment]
I think I see part of the problem. We're off to a great start with grid, but we can leverage that with media queries.

**Comment by tanyagupta** [comment]
This is super important. We have a prospective new team mate - I will flag this to her in case she is interested

**Comment by PepperAddict** [comment]
Hey if nobody steps forward to work on this, I'd like to tackle it after the sticky footer is done.

**Comment by tanyagupta** [comment]
@PepperAddict I can help if you need anything.
