### ISSUE TITLE
Static Map needs alt tag

### ISSUE THREAD

**Issue by digilou** [gwg-women/gwg-women-techmakers#98]
Related to #81 

One issue that comes up in the Dev Tools audit is that there is a missing `alt` property for the static map. The `alt` property should always be present. And since this is not a decorative image, it needs to have meaningful text within the quotes.

**Comment by digilou** [comment]
@gwg-women/all-gwg-women I can't seem to find the `img` that needs the `alt`. I'm left wondering if this is something that Google maps generates on their end? Who worked on the static maps portion?

**Comment by sonalikatara** [comment]
@digilou I don't see that error, do you have the latest dev branch. How can I recreate this error ? Can you give more deatils, maybe the file and line number ?

**Comment by agonzalez0515** [comment]
Static map still needs a lot of work and it’s not ready. I will be sure to add the alt tag when I’m ready to create a PR.

**Comment by digilou** [comment]
@sonalikatara This "error" came up when I ran the [Accessibility Audit in Chrome Dev Tools](https://developers.google.com/web/tools/lighthouse/).
@agonzalez0515 Thanks for clarifying! I won't worry about it then.

**Comment by khusbuchandra** [comment]
@agonzalez0515 , @digilou , Can we close this issue now with reference to  #113

**Comment by agonzalez0515** [comment]
Fixed with #113
